repos:
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: 4afcaa82fc368d40d486256bf4edba329bf667bb
    hooks:
      - id: dart-format
        args: [
            apps/example
            packages/flutter_locations
            packages/dart_locations_repository_interface,
          ]
      - id: flutter-analyze
        args: [
            apps/example
            packages/flutter_locations
            packages/dart_locations_repository_interface,
          ]
