name: dart_locations_repository_interface
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ^3.4.3

dependencies:
  rxdart: ^0.28.0

dev_dependencies:
  test: ^1.24.0
  mocktail: ^1.0.4
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
