name: example
description: "Flutter Locations userstory example app"

version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_locations:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.0.0
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0

flutter:
  uses-material-design: true
