name: flutter_locations
description: "A user story regarding anything that has to do with a location. From finding items on a map, calculating a route and tracking your movement."
version: 0.0.1
homepage: https://github.com/Iconica-Development

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_locations_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.0.0
  flutter_hooks: ^0.18.4
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  platform_maps_flutter: ^1.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
